export const strongSubscriptionPhrases = [
    "you've successfully subscribed",
    "you have successfully subscribed",
    "your subscription will",
    "your subscription has",
    "your subscription is",
    "your subscription with",
    "your membership will",
    "your membership has",
    "your membership is",
    "subscription will renew",
    "subscription has renewed",
    "subscription was renewed",
    "membership will renew",
    "membership has renewed",
    "set to renew",
    "set to renew automatically",
    "will renew automatically",
    "renewed automatically",
    "automatic renewal",
    "auto-renewal",
    "auto renewal",
    "next billing date",
    "next payment date",
    "you will be charged",
    "you were charged",
    "we charged you",
    "subscription will end",
    "subscription has ended",
    "subscription was cancelled",
    "subscription was canceled",
];

export const ownershipPhrases = [
    "your subscription",
    "your membership",
    "you've successfully subscribed",
    "you have successfully subscribed",
    "subscription with",
    "manage your subscription",
    "manage subscription",
    "cancel your subscription",
    "cancel subscription",
    "your billing",
    "your renewal",
];

export const recurringPhrases = [
    "per month",
    "per year",
    "monthly",
    "yearly",
    "annually",
    "every month",
    "every year",
    "billing cycle",
    "next billing",
    "next payment",
    "renew automatically",
    "automatic renewal",
    "auto-renewal",
    "auto renewal",
];

export const promotionalPhrases = [
    "become a member",
    "join today",
    "join now",
    "subscribe now",
    "sign up today",
    "sign up now",
    "start your free trial",
    "start a free trial",
    "limited time",
    "for a limited time",
    "offer ends",
    "offer ends soon",
    "sale ends",
    "founding member pricing",
    "founding member prices",
    "pricing ends",
    "prices end",
    "save 50%",
    "50% off",
    "upgrade today",
    "upgrade now",
    "get started today",
    "get started now",
];

export const nonPaidPhrases = [
    "free newsletter",
    "newsletter subscription",
    "subscribe to our newsletter",
    "subscribe to this newsletter",
    "subscribe to this list",
    "subscribed to this list",
    "mailing list",
    "status page",
    "status notifications",
    "notification subscription",
    "email subscription",
    "email notifications",
];
